import Header from "./components/Header";
import Footer from "./components/Footer";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="p-10 min-h-full	">
                    <Header />
                    <div className="p-10">{children}</div>

                    <div>
                        <Footer />
                    </div>
                </div>
            </body>
        </html>
    );
}
